### ISSUE TITLE
Planning

### ISSUE THREAD

**Issue by jonathandhill** [SchoolOfCode/bc17-w8d1-workshop-react-flashcards-v2-code_kitchen#4]
```[tasklist]
### Tasks
- [x] Folder structure
- [ ] Where state lives (each flashcard has state for open/closed, another [flashcards] in the parent component)
- [ ] CSS layout
- [ ] Create Form to be able to change / edit question and answer
- [ ] App is main parent folder for children. One sub child folder for flashcards
- [ ] Plan which props to use and where (including setter functions)
```
